[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["cd python-backend && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd python-backend && python main.py"
