[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "cd python-backend && python -m venv /opt/venv",
  "cd python-backend && /opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd python-backend && /opt/venv/bin/python main.py"
