[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# These will be set in Railway dashboard
# ANTHROPIC_API_KEY
# LANGFUSE_SECRET_KEY
# LANGFUSE_PUBLIC_KEY
# LANGFUSE_BASE_URL
# PORT
