# render.yaml - Render configuration
services:
  - type: web
    name: business-partner-ai
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_BASE_URL
        value: https://us.cloud.langfuse.com
      - key: PORT
        value: 8000
